<a href="https://colab.research.google.com/github/serrve1/AlphaRisk/blob/main/EDA(4%EB%B2%88).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
from pprint import pprint
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')

In [5]:
df = pd.read_csv('/content/drive/MyDrive/프로젝트2/데이터수집/df_label4.csv', encoding='cp949', index_col=0)
df.head()

회사명   거래소코드     회계년도     매출액증가율   정상영업이익증가율      순이익증가율    총자본증가율  \
0  (주)DB하이텍     990  2013/12 -16.424624  -38.478818  164.975353 -8.582403   
1  (주)HJ중공업   97230  2013/12  -0.783660 -231.485051  257.411583  1.492553   
2    (주)STX   11810  2014/12 -33.265072 -103.710947 -123.851645 -6.518935   
3  (주)TCC스틸    2710  2014/12   3.626457 -104.447243  -20.756942  1.341154   
5  (주)강원에너지  114190  2018/12   4.718162 -106.107690 -126.486902  0.714946   

     유동자산증가율   비유동자산증가율    유형자산증가율  ...  자기자본회전률  재고자산회전기간  매출채권회전기간  \
0 -27.878078  -1.553097 -27.878078  ...     1.99     56.05     47.13   
1  22.631893  -9.659531  22.631893  ...     1.51     59.57     33.75   
2  12.601073 -34.162244  12.601073  ...     0.00     33.69     54.17   
3   5.994190  -1.821999   5.994190  ...     2.63     84.93     54.33   
5   3.655600  -7.256298   3.655600  ...     1.74      1.92    185.05   

   매입채무회전기간  합계_1인년간평균급여  합계_평균근속연수  감사의견코드    회계기준    년도  label  
0     17.54      47000.0        7.5      UQ  IFRS연결  2013      1  
1     34.37      52667.0       14.9      UQ  IFRS연결  2013      1  
2     36.54      47000.0        4.6      UQ  IFRS연결  2014      1  
3     26.97      63000.0      16.1년      UQ  IFRS연결  2014      1  
5     56.25      46415.0      6년7개월      UQ  IFRS연결  2018      1  

[5 rows x 65 columns]

In [6]:
label_0 = df[df['label'] == 0]
label_1 = df[df['label'] == 1]

In [7]:
display(label_0.describe())
display(label_1.describe())

거래소코드        매출액증가율     정상영업이익증가율         순이익증가율        총자본증가율  \
count   12228.000000  12228.000000  12228.000000   12228.000000  12228.000000   
mean    79042.787864     14.549080      1.351615      -4.701063      9.784733   
std    102421.719249    371.582071    883.520835    5055.667143     31.191639   
min        20.000000    -99.686397 -53516.842967 -321987.015504    -88.759415   
25%     12790.000000     -3.115492    -40.656264     -62.677504     -0.054970   
50%     47050.000000      5.257065      0.000000      -5.489904      5.255471   
75%    100220.000000     16.590904     35.493745      42.713657     13.550352   
max    950220.000000  40693.187936  26620.871139  339519.403249   1720.861203   

            유동자산증가율      비유동자산증가율       유형자산증가율          배당성향      자기자본순이익률  \
count  12228.000000  12228.000000  12228.000000  12186.000000  12228.000000   
mean      10.616337     13.624834     10.616337     38.832793      6.270693   
std       45.584226     52.743392     45.584226    674.726173     23.359143   
min      -95.417548    -91.526641    -95.417548      0.000000  -1073.220000   
25%       -4.047346     -1.609661     -4.047346      0.000000      2.390000   
50%        5.498002      4.143538      5.498002     14.360000      6.680000   
75%       17.746951     15.356223     17.746951     31.030000     12.080000   
max     3110.467872   2005.638214   3110.467872  68936.100000    428.570000   

       ...       유형자산회전율       경영자본회전률       유동자산회전률       자기자본회전률  \
count  ...  12228.000000  12228.000000  12228.000000  12228.000000   
mean   ...     12.326546      1.120178      2.017255      1.899612   
std    ...     73.040996      0.615098      1.212840      1.688218   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      1.890000      0.730000      1.240000      0.900000   
50%    ...      3.130000      1.010000      1.800000      1.450000   
75%    ...      5.770000      1.370000      2.520000      2.320000   
max    ...   4314.180000     10.130000     17.770000     29.750000   

            재고자산회전기간      매출채권회전기간      매입채무회전기간    합계_1인년간평균급여            년도  \
count   12228.000000  12228.000000  12228.000000   12228.000000  12228.000000   
mean       72.833853     65.776317     35.249199   53671.226775   2017.498446   
std      2307.508284    160.763059    467.251884   22214.627939      3.154522   
min         0.000000     -4.740000      0.000000       0.000000   2012.000000   
25%        18.307500     37.917500     15.010000   41000.000000   2015.000000   
50%        40.975000     55.805000     25.330000   50000.000000   2018.000000   
75%        68.390000     77.500000     39.020000   62000.000000   2020.000000   
max    254780.810000  13774.300000  50880.470000  579000.000000   2022.000000   

         label  
count  12228.0  
mean       0.0  
std        0.0  
min        0.0  
25%        0.0  
50%        0.0  
75%        0.0  
max        0.0  

[8 rows x 59 columns]

거래소코드       매출액증가율     정상영업이익증가율        순이익증가율      총자본증가율  \
count     866.000000   866.000000    866.000000  8.660000e+02  866.000000   
mean    89372.390300    20.873503    -40.958302  2.443472e+03    1.575146   
std    105430.455452   328.337677   1009.850416  7.590779e+04   44.019649   
min        40.000000   -98.900713 -13487.874412 -2.587189e+04  -93.406284   
25%     24815.000000   -20.717126    -84.801491 -8.124170e+01  -14.679439   
50%     62160.000000    -3.580473    -20.504688 -1.570595e+01   -3.685293   
75%    112190.000000    13.277464     55.045423  8.211866e+01    6.668466   
max    950200.000000  8891.345479  10313.110108  2.233014e+06  522.609302   

           유동자산증가율     비유동자산증가율      유형자산증가율        배당성향       자기자본순이익률  ...  \
count   866.000000   866.000000   866.000000  863.000000     866.000000  ...   
mean      4.525444     9.257155     4.525444    3.973685    -161.833580  ...   
std      66.074747    89.516651    66.074747   31.548970    3436.695046  ...   
min     -97.708346   -96.959219   -97.708346    0.000000 -101015.660000  ...   
25%     -24.034366   -14.418153   -24.034366    0.000000     -45.062500  ...   
50%      -5.460690    -3.507973    -5.460690    0.000000     -18.070000  ...   
75%      12.447820     9.569314    12.447820    0.000000      -4.102500  ...   
max    1024.358609  1457.131930  1024.358609  696.140000      92.610000  ...   

           유형자산회전율     경영자본회전률     유동자산회전률     자기자본회전률     재고자산회전기간  \
count   866.000000  866.000000  866.000000  866.000000   866.000000   
mean     14.315889    0.786755    1.515531    1.838995    72.333776   
std     143.233381    0.590047    1.180549    2.377080   104.637287   
min       0.000000    0.000000    0.000000    0.000000     0.000000   
25%       1.050000    0.420000    0.750000    0.515000    22.802500   
50%       2.085000    0.670000    1.310000    1.200000    50.740000   
75%       4.322500    1.020000    2.007500    2.237500    89.020000   
max    4055.070000    7.460000   14.100000   36.170000  1394.720000   

          매출채권회전기간    매입채무회전기간    합계_1인년간평균급여           년도  label  
count   866.000000   866.00000     866.000000   866.000000  866.0  
mean     79.585127    41.59903   44526.069284  2016.565820    1.0  
std     107.771472    66.81312   14357.479802     3.278719    0.0  
min       0.000000     0.00000       0.000000  2012.000000    1.0  
25%      40.892500    14.74250   35373.750000  2013.000000    1.0  
50%      61.165000    30.16000   43439.500000  2016.000000    1.0  
75%      90.417500    53.96750   51000.000000  2020.000000    1.0  
max    1893.160000  1418.31000  129000.000000  2022.000000    1.0  

[8 rows x 59 columns]

In [8]:
mean_by_label = df.groupby('label').mean()
mean_by_label

거래소코드     매출액증가율  정상영업이익증가율       순이익증가율    총자본증가율    유동자산증가율  \
label                                                                         
0      79042.787864  14.549080   1.351615    -4.701063  9.784733  10.616337   
1      89372.390300  20.873503 -40.958302  2443.471841  1.575146   4.525444   

        비유동자산증가율    유형자산증가율       배당성향    자기자본순이익률  ...   당좌자산회전률    유형자산회전율  \
label                                               ...                        
0      13.624834  10.616337  38.832793    6.270693  ...  2.818683  12.326546   
1       9.257155   4.525444   3.973685 -161.833580  ...  2.140115  14.315889   

        경영자본회전률   유동자산회전률   자기자본회전률   재고자산회전기간   매출채권회전기간   매입채무회전기간  \
label                                                                  
0      1.120178  2.017255  1.899612  72.833853  65.776317  35.249199   
1      0.786755  1.515531  1.838995  72.333776  79.585127  41.599030   

        합계_1인년간평균급여           년도  
label                             
0      53671.226775  2017.498446  
1      44526.069284  2016.565820  

[2 rows x 58 columns]

In [9]:
big_label0 = []
big_label1 = []

# 각 레이블에 대한 평균값 계산
mean_by_label = df.groupby('label').mean()

# 각 컬럼에 대해 레이블 1과 레이블 0의 평균값 비교
for column in mean_by_label.columns:
    if column != 'label':  # 레이블 컬럼은 제외
        mean_label_1 = mean_by_label.loc[1, column]
        mean_label_0 = mean_by_label.loc[0, column]

        if mean_label_1 > mean_label_0:
            # print(f"레이블 1의 {column} 평균이 레이블 0의 평균보다 높습니다.")
            big_label1.append(column)

        elif mean_label_1 < mean_label_0:
            # print(f"레이블 1의 {column} 평균이 레이블 0의 평균보다 낮습니다.")
            big_label0.append(column)
        else:
            print(f"레이블 1과 레이블 0의 {column} 평균이 같습니다.")

In [10]:
big_label1

['거래소코드',
 '매출액증가율',
 '순이익증가율',
 '자기주식',
 '부채비율',
 '차입금의존도',
 '유동부채비율',
 '비유동장기적합률',
 '매출채권회전률',
 '유형자산회전율',
 '매출채권회전기간',
 '매입채무회전기간']

In [11]:
big_label0

['정상영업이익증가율',
 '총자본증가율',
 '유동자산증가율',
 '비유동자산증가율',
 '유형자산증가율',
 '배당성향',
 '자기자본순이익률',
 '매출액순이익률',
 '총자본순이익률',
 '경영자본순이익률',
 '총자본사업이익률',
 '총자본정상영업이익률',
 '매출액정상영업이익률',
 'CASH FLOW 대 부채비율',
 'CASH FLOW 대 차입금비율',
 'CASH FLOW 대 총자본비율',
 'CASH FLOW 대 매출액비율',
 '영업활동으로 인한 현금흐름(간접법)(*)',
 '금융비용',
 '단기차입금(*)',
 '유동성장기차입금의 감소',
 '부가가치',
 '총자본투자효율',
 '설비투자효율',
 '부가가치율',
 '이윤분배율',
 '자본분배율',
 '유동자산(*)',
 '유동부채(*)',
 '유동비율',
 '당좌비율',
 '순운전자본비율',
 '현금비율',
 '유동자산구성비율',
 '자기자본구성비율',
 '재고자산회전률',
 '매입채무회전률',
 '총자본회전률',
 '비유동자산회전률',
 '당좌자산회전률',
 '경영자본회전률',
 '유동자산회전률',
 '자기자본회전률',
 '재고자산회전기간',
 '합계_1인년간평균급여',
 '년도']

In [12]:
display(label_0[big_label1].describe())
display(label_1[big_label1].describe())

거래소코드        매출액증가율         순이익증가율          자기주식          부채비율  \
count   12228.000000  12228.000000   12228.000000  1.222800e+04  12228.000000   
mean    79042.787864     14.549080      -4.701063 -2.676534e+07     93.417338   
std    102421.719249    371.582071    5055.667143  2.462459e+08    163.039672   
min        20.000000    -99.686397 -321987.015504 -1.344102e+10      0.000000   
25%     12790.000000     -3.115492     -62.677504 -6.265148e+06     29.970000   
50%     47050.000000      5.257065      -5.489904 -1.272037e+06     61.945000   
75%    100220.000000     16.590904      42.713657  0.000000e+00    118.077500   
max    950220.000000  40693.187936  339519.403249  0.000000e+00  13206.810000   

             차입금의존도        유동부채비율      비유동장기적합률       매출채권회전률       유형자산회전율  \
count  12228.000000  12228.000000  12228.000000  12228.000000  12228.000000   
mean      18.498810     66.669836     71.971322      9.399456     12.326546   
std       17.526696    115.256670     34.889197     18.207392     73.040996   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        3.650000     22.180000     50.267500      4.690000      1.890000   
50%       15.790000     43.685000     68.720000      6.520000      3.130000   
75%       29.792500     83.085000     89.462500      9.570000      5.770000   
max      749.400000   9345.580000    890.390000    619.690000   4314.180000   

           매출채권회전기간      매입채무회전기간  
count  12228.000000  12228.000000  
mean      65.776317     35.249199  
std      160.763059    467.251884  
min       -4.740000      0.000000  
25%       37.917500     15.010000  
50%       55.805000     25.330000  
75%       77.500000     39.020000  
max    13774.300000  50880.470000

거래소코드       매출액증가율        순이익증가율          자기주식          부채비율  \
count     866.000000   866.000000  8.660000e+02  8.660000e+02    866.000000   
mean    89372.390300    20.873503  2.443472e+03 -7.173201e+06    329.780323   
std    105430.455452   328.337677  7.590779e+04  6.132302e+07   2418.514023   
min        40.000000   -98.900713 -2.587189e+04 -1.272692e+09      0.000000   
25%     24815.000000   -20.717126 -8.124170e+01 -2.645194e+06     56.140000   
50%     62160.000000    -3.580473 -1.570595e+01 -2.023450e+05    118.525000   
75%    112190.000000    13.277464  8.211866e+01  0.000000e+00    212.500000   
max    950200.000000  8891.345479  2.233014e+06  0.000000e+00  65433.660000   

           차입금의존도        유동부채비율     비유동장기적합률      매출채권회전률      유형자산회전율  \
count  866.000000    866.000000   866.000000   866.000000   866.000000   
mean    34.011767    260.356351   108.285266    11.104850    14.315889   
std     21.454324   2232.607695   148.599392    60.381496   143.233381   
min      0.000000      0.000000     0.000000     0.000000     0.000000   
25%     19.027500     34.005000    59.645000     3.962500     1.050000   
50%     33.330000     87.785000    92.780000     5.910000     2.085000   
75%     47.747500    166.350000   122.207500     8.835000     4.322500   
max    190.320000  62593.500000  3635.590000  1596.020000  4055.070000   

          매출채권회전기간    매입채무회전기간  
count   866.000000   866.00000  
mean     79.585127    41.59903  
std     107.771472    66.81312  
min       0.000000     0.00000  
25%      40.892500    14.74250  
50%      61.165000    30.16000  
75%      90.417500    53.96750  
max    1893.160000  1418.31000

In [13]:
def cut_top_bottom(dfs, col) :
  # 특정 열의 상위 1%와 하위 1% 값을 계산
  top_1_percent = dfs[col].quantile(0.99)
  bottom_1_percent = dfs[col].quantile(0.01)

  # 상위 1%와 하위 1%를 제외한 데이터 선택
  filtered_df = dfs[(dfs[col] > bottom_1_percent) & (df[col] < top_1_percent)]
  display(filtered_df.groupby('label').mean()[col])

In [14]:
def winsorize(dfs, col):
    # 특정 열의 상위 1%와 하위 1% 값을 계산
    top_1_percent = dfs[col].quantile(0.99)
    bottom_1_percent = dfs[col].quantile(0.01)

    # 상위 1%와 하위 1%를 제외한 값으로 이상치 대체
    dfs[col] = np.where(dfs[col] > top_1_percent, top_1_percent, dfs[col])
    dfs[col] = np.where(dfs[col] < bottom_1_percent, bottom_1_percent, dfs[col])

    print(dfs.groupby('label').mean()[col])

In [15]:
winsorize(df, '유형자산회전율')

label
0    8.985553
1    8.001422
Name: 유형자산회전율, dtype: float64




+ 처음에는 매출액증가율,	자기주식,	부채비율,	차입금의존도,	유동부채비율,	현금비율,	비유동장기적합률,	매출채권회전률,	유형자산회전율,	매출채권회전기간,	매입채무회전기간에서 부실기업 평균이 정상기업 평균보다 높은 문제가 있었음. </br>
하지만 부채비율, 차입금의존도, 유동부채비율, 매출채권회전기간, 매입채무회전기간은 부실기업이 정상기업보다 높은게 일반적이지만 나머지 변수들은 아니기 때문에 윈저라이징을 진행하고 다시 평균값을 비교한 결과입니다.

+ 윈저라이징 진행
  + 매출액증가율 (상하위 1%로 설정할 경우 정상기업 > 부실기업)
  + 자기주식은 안됨
  + 현금비율 (상하위 1%로 설정할 경우 정상기업 > 부실기업)
  + 비유동장기적합률은 안됨
  + 매출채권회전률 (상하위 1%로 설정할 경우 정상기업 > 부실기업)
  + 유형자산회전율 (상하위 1%로 설정할 경우 정상기업 > 부실기업)
+결과적으로 자기주식과 미유동장기적합률을 제외한 값은 윈저라이징 이후에 평균값이 정상기업이 부실기업보다 높게 변함

##### 기타법인 처리하기

In [20]:
s1 = df["회사명"].unique().tolist()
s2 = df["거래소코드"].unique().tolist()
s_cop_code = []
s_cop_name = []

for i in s1 :
  find_cop = df[df['회사명'] == i]
  code = find_cop['거래소코드'].unique()
  if len(code) >= 2:
    # print(len(code))
    s_cop_code.append(code)
    s_cop_name.append(i)


In [21]:
s_cop_code

[array([182400, 262760]),
 array([  830, 28260]),
 array([ 3600, 34730]),
 array([323230, 251960]),
 array([ 2300, 27970]),
 array([220250, 284620]),
 array([ 60540, 158300]),
 array([131390, 217820]),
 array([ 62580, 277410]),
 array([224090, 208140]),
 array([284610, 317240]),
 array([176560, 256630]),
 array([284420, 353190]),
 array([144630, 222080]),
 array([239340, 229480]),
 array([ 85980, 252500]),
 array([237720, 225430])]